package com.hamsuhi.entity;
// Generated Mar 7, 2018 1:58:59 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

import net.minidev.json.annotate.JsonIgnore;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "booking_manager")
public class Booking implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer bookingId;
	private String bookName;
	private String publisher;
	private String bookingcol;
	private Set<BookBorrowing> bookBorrowings = new HashSet<BookBorrowing>(0);

	public Booking() {
	}
	

	public Booking(String bookName, String publisher, String bookingcol) {
		super();
		this.bookName = bookName;
		this.publisher = publisher;
		this.bookingcol = bookingcol;
	}


	public Booking(Integer bookingId, String bookName, String publisher, String bookingcol) {
		super();
		this.bookingId = bookingId;
		this.bookName = bookName;
		this.publisher = publisher;
		this.bookingcol = bookingcol;
	}


	public Booking(String bookName, String publisher, String bookingcol, Set<BookBorrowing> bookBorrowings) {
		this.bookName = bookName;
		this.publisher = publisher;
		this.bookingcol = bookingcol;
		this.bookBorrowings = bookBorrowings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "booking_id", unique = true, nullable = false)
	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "book_name", length = 45)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "publisher", length = 45)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "bookingcol", length = 45)
	public String getBookingcol() {
		return this.bookingcol;
	}

	public void setBookingcol(String bookingcol) {
		this.bookingcol = bookingcol;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "booking")
	@JsonBackReference
	public Set<BookBorrowing> getBookBorrowings() {
		return this.bookBorrowings;
	}

	public void setBookBorrowings(Set<BookBorrowing> bookBorrowings) {
		this.bookBorrowings = bookBorrowings;
	}

}
