package com.hamsuhi.entity;
// Generated Mar 7, 2018 1:58:59 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;

import net.minidev.json.annotate.JsonIgnore;

/**
 * Reader generated by hbm2java
 */
@Entity
@Table(name = "reader", catalog = "booking_manager")
public class Reader implements java.io.Serializable {

	private static final long serialVersionUID = 1L;;
	private Integer numberCard;
	private String readerName;
	private Date dateRange;
	private String tel;
	private Set<BookBorrowing> bookBorrowings = new HashSet<BookBorrowing>(0);

	public Reader() {
	}

	public Reader(String readerName, Date dateRange, String tel) {
		super();
		this.readerName = readerName;
		this.dateRange = dateRange;
		this.tel = tel;
	}

	public Reader(Integer numberCard, String readerName, Date dateRange, String tel) {
		super();
		this.numberCard = numberCard;
		this.readerName = readerName;
		this.dateRange = dateRange;
		this.tel = tel;
	}

	public Reader(String readerName, Date dateRange, String tel, Set<BookBorrowing> bookBorrowings) {
		this.readerName = readerName;
		this.dateRange = dateRange;
		this.tel = tel;
		this.bookBorrowings = bookBorrowings;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "number_card", unique = true, nullable = false)
	public Integer getNumberCard() {
		return this.numberCard;
	}

	public void setNumberCard(Integer numberCard) {
		this.numberCard = numberCard;
	}

	@Column(name = "reader_name", length = 45)
	public String getReaderName() {
		return this.readerName;
	}

	public void setReaderName(String readerName) {
		this.readerName = readerName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_range", length = 10)
	@JsonFormat(shape=JsonFormat.Shape.STRING,pattern="dd/MM/yyyy")
	public Date getDateRange() {
		return this.dateRange;
	}

	public void setDateRange(Date dateRange) {
		this.dateRange = dateRange;
	}

	@Column(name = "tel", length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "reader")
	@JsonBackReference
	public Set<BookBorrowing> getBookBorrowings() {
		return this.bookBorrowings;
	}

	public void setBookBorrowings(Set<BookBorrowing> bookBorrowings) {
		this.bookBorrowings = bookBorrowings;
	}

}
