package com.hamsuhi.entity;
// Generated Mar 7, 2018 1:58:59 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookBorrowingId generated by hbm2java
 */
@Embeddable
public class BookBorrowingId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int numberCard;
	private int bookingId;

	public BookBorrowingId() {
	}

	public BookBorrowingId(int numberCard, int bookingId) {
		this.numberCard = numberCard;
		this.bookingId = bookingId;
	}

	@Column(name = "number_card", nullable = false)
	public int getNumberCard() {
		return this.numberCard;
	}

	public void setNumberCard(int numberCard) {
		this.numberCard = numberCard;
	}

	@Column(name = "booking_id", nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookBorrowingId))
			return false;
		BookBorrowingId castOther = (BookBorrowingId) other;

		return (this.getNumberCard() == castOther.getNumberCard()) && (this.getBookingId() == castOther.getBookingId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumberCard();
		result = 37 * result + this.getBookingId();
		return result;
	}

}
